# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk11

env:
  global:
    CODECOV_TOKEN="c4e65d1f-03e7-4b27-bd5a-fe7a1756c298"

# используем режим обычного пользователя для сборки проекта.
sudo: false

# Отправлять уведомление на почту если сборка упала
notifications:
  email:
    recipients:
      Meng263@gmail.com
    on_success: never # default: change
    on_failure: always # default: always